### PR TITLE
enable trivy scanning for nginx

### PR DESCRIPTION
**Pull request by manishkumr**

### CODE REVIEW

**Comment by manishkumr** [comment]
Sorry..wrong base repo selected for this PR. I will close this.

**Comment by manishkumr** [comment]
For my fork of this repo, I have created a [github action workflow](https://github.com/MonashBI/xnat-docker-compose/pull/25) to scan nginx, tomcat, postgres containers using [trivy](https://github.com/aquasecurity/trivy). This [reports](https://github.com/MonashBI/xnat-docker-compose/runs/2162972214?check_suite_focus=true) any known security vulneralabilities in these containers. Happy to submit a PR if you guys think this will be helpful.

**Comment by rherrick** [comment]
Please do submit at PR, this is really helpful!

**Comment by manishkumr** [comment]
Hi @rherrick Yes sure, here is the PR #65

**Pull request closed without merging**
