### PR TITLE
Modified ubuntu jdk7 image to tomcat:7-jre7-alpine (Rebased)

### LINKED ISSUE #3: Replace manishkumr/ubuntu_jdk7_image base tomcat7 base container
It would be good to replace the manishkumr/ubuntu_jdk7_image base with a new image built from a dockerfile

### PR DESCRIPTION
**Pull request by johnflavin**
This is a cleaned-up version of PR #6, rebased on master.

Closes #3
Closes #6

### CODE REVIEW

**Comment by manishkumr** [comment]
Great work guys 👍 

Just wanted add few more thoughts from my side 

- [ ] It would be great to have all tomcat configuration(TOMCAT-HOME/conf/) exposed as volume on docker host. 
This will allow configuration changes to persist between container restarts and will also make easier to view/modify tomcat configs.

**Comment by johnflavin** [comment]
> @manishkumr It would be great to have all tomcat configuration(TOMCAT-HOME/conf/) exposed as a volume on docker host.
This will allow configuration changes to persist between container restarts and will also make easier to view/modify tomcat configs.

That makes sense. And since that is functionality that is present in the code we got from you but is being removed by this PR, it is a bit of a regression to no longer be able to change any tomcat settings.

**Comment by johnflavin** [comment]
Quoting @manishkumr from [this comment on #8](https://github.com/NrgXnat/xnat-docker-compose/pull/8#issuecomment-337467155):

> I was under impression that XNAT requires JDK instead of JRE, and this was one of the reason to use pre-built ubuntu-JDK-7 image. May be I have missed something.. Does this [documentation](https://wiki.xnat.org/documentation/getting-started-with-xnat-1-7/installing-xnat-1-7/prerequisites-for-installing-xnat-1-7) still valid ?

That is a good point, and something I hadn't even thought about. I honestly forgot the recommendation to install the JDK over the JRE. 

I have been able to use this branch to start up the XNAT and log in and such, so I know that things work to at least that bare minimum. But I haven't put it through its paces. There is no guarantee that everything in the site will work properly with the JRE.

Maybe we should keep this PR on hold for a bit until we can answer this question. Because if we do need the JDK, then this PR is fundamentally flawed.

**Comment by tclose** [comment]
At the workshop it was raised (I can't remember who by) that perhaps the JDK recommendation is a hangover from 1.6 where the installation procedure involved some compilation. Can you check this with Rick, Flavin?

**Comment by rherrick** [comment]
Tomcat requires the JDK whenever run-time compilation is required, which is most the time. And XNAT 1.7 (even a little bit before that) does require run-time compilation, with JSP pages, tag files, and a number of other features. So basic functions might work (older pages are based on Velocity templates, which uses another engine for rendering), REST calls are stand-alone code, but most of the new UI is coded in JSP pages.

So you don’t have the specific build stage when installing or updating the app, but the JDK is required for run-time.

XNAT is fully compatible with JDK 1.8/Java 8 (although built to Java 7 Byte code) so that’s another option (and possibly a recommended option, due to improvements in 1.8 in performance and memory management, as well as being compatible with a future XNAT version that might be built to Java 8 byte code).

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tclose** [comment]
Thanks for the update Rick. So the issue is that there isn't an officially supported tomcat docker image that uses jdk (they all just use jre). However, we could just copy the source from the jre-8 dockerfile, https://github.com/docker-library/tomcat/blob/5a78361a9ce7ef48979acbcabe2acd9342d0168a/8.5/jre8/Dockerfile, into our tomcat dockerfile and change the FROM tag to openjdk:8-jdk

**Comment by rherrick** [comment]
Actually, my information appears to be out of date ☺ It used to be that Tomcat required the JDK but apparently they started bundling the Eclipse compiler with the release of Tomcat 7. So never mind what I said.

I’d still recommend the Java 8 version, but that’s a nice-to-have, not a need-to-have.

--
Rick Herrick
Sr. Programmer/Analyst
Neuroinformatics Research Group
Washington University School of Medicine

Voice: (314) 273-1645
Web: http://www.xnat.org<http://www.xnat.org/>
Twitter: @NrgXnat<https://twitter.com/nrgxnat>

**Comment by tclose** [comment]
Okay, so it appears this PR is good to merge then. Maybe just update the jre version to 8 as Rick suggests.

**Comment by Sikerdebaard** [comment]
When changing the xnat17/Dockerfile from tomcat:7-jre7-alpine to tomcat:8-jre8-alpine the following error occurs. I haven't had time to figure out why it happens yet. Should we fix this for this pr or shall we consider it out-of-scope and make a new pr?

```
➜  xnat-docker-compose git:(pr6-rebase) ✗ docker logs 32ce05722c3b
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
25-Oct-2017 08:58:40.956 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.23
25-Oct-2017 08:58:40.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 28 2017 10:30:11 UTC
25-Oct-2017 08:58:40.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.23.0
25-Oct-2017 08:58:40.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
25-Oct-2017 08:58:40.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.12.9-300.fc26.x86_64
25-Oct-2017 08:58:40.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
25-Oct-2017 08:58:40.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
25-Oct-2017 08:58:40.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_131-b11
25-Oct-2017 08:58:40.970 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
25-Oct-2017 08:58:40.970 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
25-Oct-2017 08:58:40.970 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
25-Oct-2017 08:58:40.970 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
25-Oct-2017 08:58:40.971 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
25-Oct-2017 08:58:40.972 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
25-Oct-2017 08:58:40.974 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
25-Oct-2017 08:58:40.974 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms128m
25-Oct-2017 08:58:40.975 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024m
25-Oct-2017 08:58:40.975 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=256m
25-Oct-2017 08:58:40.975 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
25-Oct-2017 08:58:40.975 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
25-Oct-2017 08:58:40.975 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
25-Oct-2017 08:58:40.975 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.14] using APR version [1.5.2].
25-Oct-2017 08:58:40.976 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
25-Oct-2017 08:58:40.976 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
25-Oct-2017 08:58:40.979 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.2k  26 Jan 2017]
25-Oct-2017 08:58:41.150 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
25-Oct-2017 08:58:41.190 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
25-Oct-2017 08:58:41.192 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
25-Oct-2017 08:58:41.195 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
25-Oct-2017 08:58:41.195 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 890 ms
25-Oct-2017 08:58:41.232 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
25-Oct-2017 08:58:41.232 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.23
25-Oct-2017 08:58:41.257 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
25-Oct-2017 08:58:41.314 SEVERE [localhost-startStop-1] org.apache.tomcat.util.digester.Digester.startElement Begin event threw exception
 java.lang.ClassNotFoundException: org.apache.catalina.loader.VirtualWebappLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:116)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1249)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1517)
	at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:537)
	at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:494)
	at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:738)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:310)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:108)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1144)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1878)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

25-Oct-2017 08:58:41.316 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.processContextConfig Parse error in context.xml for []
 org.xml.sax.SAXParseException; systemId: file:/usr/local/tomcat/webapps/ROOT/META-INF/context.xml; lineNumber: 12; columnNumber: 145; Error at (12, 145) : org.apache.catalina.loader.VirtualWebappLoader
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1967)
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1999)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1252)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1517)
	at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:537)
	at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:494)
	at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:738)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:310)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:108)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1144)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1878)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.loader.VirtualWebappLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:116)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1249)
	... 30 more

25-Oct-2017 08:58:41.317 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.processContextConfig Occurred at line [12] column [145]
25-Oct-2017 08:58:42.624 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.configureStart Marking this application unavailable due to previous error(s)
25-Oct-2017 08:58:42.634 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more components marked the context as not correctly configured
25-Oct-2017 08:58:42.662 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
25-Oct-2017 08:58:42.676 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [1,418] ms
25-Oct-2017 08:58:42.678 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
25-Oct-2017 08:58:42.685 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
25-Oct-2017 08:58:42.686 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 1490 ms
```

**Comment by johnflavin** [comment]
That stacktrace is using an image that not only has Java 8, but also has tomcat 8. If I remember correctly, there are known issues running XNAT on tomcat 8. So we certainly want to use tomcat 7. 

If there is an image that runs tomcat 7 on Java 8, I would prefer that one over tomcat 7 on Java 7. But if the former doesn’t exist, the latter will suffice.

**Comment by Sikerdebaard** [comment]
Seems like there is a tomcat:7-jre8-alpine. At first glance it works. I'm not sure how to test xnat properly.

**Comment by johnflavin** [comment]
I have picked this back up. I'd like to merge it if no one has any objections.

**Pull request merged**
